#!/bin/sh
# connect network drives

cmd //c 'net use h: \\wb-rb3-file-01\home$\JInman /y' > /dev/null 2>&1
cmd //c 'net use r: \\ca.epa.local\RB /y' > /dev/null 2>&1
cmd //c 'net use s: \\ca.epa.local\SB /y' > /dev/null 2>&1
