#!/bin/sh

# ltr: local to remote 
# translate local path to remote path

local="/home/jfin/rdrive"
remote="/r/RB3/Shared"

# if root of $PWD is same as $local
if [ "${1:0:${#local}}"  != "$local"  ] 
then
	exit
else
	echo -n "$remote${1#$local}"
fi
