#!/bin/sh

# pandoc wrapper used primarily to convert markdown notes into pdf

doc="${1%.txt}"

pandoc "${doc}".txt --output="${doc}".pdf \
	--variable=geometry:margin=1.5in \
	--variable=fontsize=12pt \
	--variable=pagestyle=empty \
	--variable=fontfamily=palatino
