#!/bin/sh

timestamp=$(date +'%Y%m%d%H%M%S')

for file in "$@";
do
	file=${file%/} # remove trailing slash of directories
	if [ ! -e "$HOME"/trash/"$file" ]
	then
		mv "$file" "$HOME"/trash
	else
		mv "$file" "$HOME"/trash/"$file"-"$timestamp"
	fi
done
