#!/bin/sh

/usr/bin/git config --global user.name "John Inman"
/usr/bin/git config --global user.email jfinmaniv@icloud.com
/usr/bin/git config --global credential.helper store

/usr/bin/git clone --bare https://github.com/jfinmaniv/dotfiles $HOME/.dotfiles
function dot {
   /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
}

dot checkout msys

if [ "$?" = 0 ]; then
  echo "Checked out dot files."
  else
    mkdir dotfiles.bak
    echo "Backing up pre-existing dot files."
	dot checkout msys 2>&1 \
    | egrep "\s+\." \
    | awk {'print $1'} \
    | xargs -I{} mv {} dotfiles.bak/{}
fi;

dot checkout msys
dot config --local status.showUntrackedFiles no
dot push --set-upstream origin msys

/usr/bin/git clone --bare https://github.com/jfinmaniv/worklogs $HOME/.worklogs
function log {
   /usr/bin/git --git-dir=$HOME/.worklogs/ --work-tree=$HOME "$@"
}
log checkout
log config --local status.showUntrackedFiles no
log push --set-upstream origin main

mkdir $HOME/.vim/undo 

for p in $(cat $HOME/.vim/plugins) 
do 
    /usr/bin/git clone https://github.com/"$p" \
    $HOME/.vim/pack/plug/start/$(echo "$p" | sed -e 's/.*\///')
done

pacman -S --noconfirm tmux python python-pip procps fzy

pip install ranger-fm
