#!/bin/sh

git config --global user.name "John Inman"
git config --global user.email jfinmaniv@icloud.com
git config --global credential.helper store

git clone --bare https://github.com/jfinmaniv/dotfiles $HOME/.dot.git
function dot {
   git --git-dir=$HOME/.dot.git/ --work-tree=$HOME "$@"
}

dot checkout obsd

if [ "$?" = 0 ]; then
  echo "Checked out dot files."
  else
    mkdir dotfiles.bak
    echo "Backing up pre-existing dot files."
	dot checkout obsd 2>&1 \
    | egrep "\s+\." \
    | awk {'print $1'} \
    | xargs -I{} mv {} dotfiles.bak/{}
fi;

dot checkout obsd
dot config --local status.showUntrackedFiles no
dot push --set-upstream origin obsd

for p in $(cat $HOME/.vim/plugins) 
do 
    git clone https://github.com/"$p" \
    $HOME/.vim/pack/plug/start/$(echo "$p" | sed -e 's/.*\///')
done

# pkg_add tmux python python-pip procps fzy
