#!/bin/sh

temp_active="$1"
temp_name=$(mktemp)
trap 'kill $(jobs -p)' HUP
while true
do
	winid=$(tail -n 1 "$temp_active" | awk '{ print $5 }')
	xprop -spy -id $winid WM_NAME > "$temp_name" &
	echo "$temp_name" | entr -np status-send-hup &
	wait
done
