#!/bin/sh

temp=$(mktemp)
trap 'kill $(jobs -p)' HUP
while true
do
	winid=$(xprop -root _NET_ACTIVE_WINDOW | awk '{ print $5 }')
	xprop -spy -id $winid WM_NAME > "$temp" &
	echo "$temp" | entr -np restart-window-watcher &
	wait
done
